# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/resume_parser_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:@chaitanya24}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CORS Configuration
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

server.port=8085
# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Configurations
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Configuration Properties
app.jwt.secret=9a67471ec639aa6e52296eef97e59c2b4c1a5b822d56a31c518a2d1f73ee9f21f1cc7c50a116b47c0b8b209e9cbcd92b217e5a02e6c86714db254ff9cf1a7746
app.jwt.expiration-ms=86400000

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key=${GEMINI_API_KEY:Resume Parser API Key}

